# Check PR titles should match conventional commits
# https://www.conventionalcommits.org/en/v1.0.0/
name: pr-title-checker
on: pull_request
jobs:
  print-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: print-pr-title
        env:
          TITLE: ${{ github.event.pull_request.title }}
        run: |
          echo "PR TITLE $TITLE"

